#!/usr/bin/env bash
# SSH client configuration

Host *
	PasswordAuthentification no
	IdentityFile ~/.ssh/school
	SendEnv Lang LC_*
	HashKnownHosts yes
	GSSAPIAuthentication yes
	GSSAPIDelegateCredentials no
